### ISSUE TITLE
Issue with the plot_histograms function ?

### ISSUE THREAD

**Issue by cdussard** [dalejn/cleanBib#56]
Hello,
Thank you for providing this tool, which seems to work great :)
I have trouble understanding the output of the plot_histograms() function
The generated percentage values I got are 10.84% woman(first)/woman(last), 20.6% man/woman, 24.27% woman/man, and 44.3% man/man. 
The references are 58.4% for man/man, 9.4% for man/woman, 25.5% for woman/man, and 6.7% for woman/woman.
![predicte_histo](https://github.com/user-attachments/assets/a9cd208a-d337-4c47-aedb-943b560f53dc)

I would expect the WW bar to be positive since the 10.84% percentage is higher than the 6.7% baserate, however it's showing up as negative. Am I misunderstanding the function or is there an error?

I attached below my predictions file if needed to reproduce the issue and the .bib file converted to .txt
[predictions.csv](https://github.com/user-attachments/files/16348248/predictions.csv) 
[citations.txt](https://github.com/user-attachments/files/16348278/citations.txt)

Thank you :)

**Comment by dalejn** [comment]
Hi, thanks for the question and for checking out this tool! It looks like the issue is that "Step 4. Describe the proportions of genders in your reference list and compare it to published base rates in neuroscience" didn't finish running before moving on to the next step. In predictions.csv, that's why only 8 out of 61 papers have a prediction whereas the rest are unknown. I just successfuly ran your citations file (after renaming it citations.bib), so I'd suggest re-running the notebook.

**Comment by cdussard** [comment]
Thank you, it worked ! 
![image](https://github.com/user-attachments/assets/c9916b2e-333f-4ef1-b7b0-d85d9b63fb99)

By the way, I think the genderAPI website updated their policy to only allow 100 predictions per month for free accounts 
![image](https://github.com/user-attachments/assets/f8add4f6-b5f2-4c5e-8bfd-fe6843827f41)
